server:
  port: 80

eureka:
  client:
    register-with-eureka: false #表示向注册中心注册自己 默认为true
    service-url:
      defaultZone: http://localhost:7001/eureka # 单机版 入驻的EurekaServer地址

feign:
  hystrix:
    enabled: true
